# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 302cc2cd9e3f4e37c959b41cb5ae3bbd690164e748e7b3c349ea438d994ea420540150c58e3d95219330382d328ec55239ca5b8260d37a40df566b66cfd7a4ca

test:
  secret_key_base: 40c0fa2169cd49b9d6258caa241b404ec779882f2b57e9fc37a0a8c5eb2e304230978f745eae0200f1e311ec10de901bc71183fe28908c796c6cb7afaa8a0702

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
